/**
 * Generate a brand guide PDF from the .brand/ directory.
 * Uses pdf-lib (no browser dependency) to build a structured PDF.
 *
 * Contents:
 * - Title page with brand name
 * - Color palette (swatches with hex values and roles)
 * - Typography (font families with weights)
 * - Logo reference (note about logo files in .brand/assets/)
 * - Visual rules summary (if Session 2 data exists)
 * - Voice summary (if Session 3 data exists)
 */

import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import type { CoreIdentityData, VisualIdentityData, MessagingData } from "../schemas/index.js";
import type { BrandConfigData } from "../schemas/brand-config.js";

function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const h = hex.replace("#", "");
  return {
    r: parseInt(h.substring(0, 2), 16) / 255,
    g: parseInt(h.substring(2, 4), 16) / 255,
    b: parseInt(h.substring(4, 6), 16) / 255,
  };
}

export async function generateBrandGuidePdf(data: {
  config: BrandConfigData;
  identity: CoreIdentityData;
  visual?: VisualIdentityData | null;
  messaging?: MessagingData | null;
}): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const helvetica = await pdf.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const PAGE_WIDTH = 595; // A4
  const PAGE_HEIGHT = 842;
  const MARGIN = 50;
  const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

  // --- Title Page ---
  const titlePage = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  titlePage.drawText(data.config.client_name, {
    x: MARGIN,
    y: PAGE_HEIGHT - 200,
    size: 36,
    font: helveticaBold,
    color: rgb(0.1, 0.1, 0.1),
  });
  titlePage.drawText("Brand Guide", {
    x: MARGIN,
    y: PAGE_HEIGHT - 245,
    size: 18,
    font: helvetica,
    color: rgb(0.4, 0.4, 0.4),
  });
  titlePage.drawText(`Generated by Brandcode MCP — ${new Date().toISOString().slice(0, 10)}`, {
    x: MARGIN,
    y: MARGIN,
    size: 9,
    font: helvetica,
    color: rgb(0.6, 0.6, 0.6),
  });

  // --- Color Palette Page ---
  const colorPage = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = PAGE_HEIGHT - MARGIN;

  colorPage.drawText("Color Palette", {
    x: MARGIN, y: y - 20, size: 24, font: helveticaBold, color: rgb(0.1, 0.1, 0.1),
  });
  y -= 60;

  const colors = data.identity.colors.filter(c => c.role !== "unknown").slice(0, 12);
  const SWATCH_SIZE = 40;
  const SWATCH_GAP = 15;
  const COLS = 3;

  for (let i = 0; i < colors.length; i++) {
    const col = i % COLS;
    const row = Math.floor(i / COLS);
    const x = MARGIN + col * (CONTENT_WIDTH / COLS);
    const sy = y - row * (SWATCH_SIZE + 50);

    if (sy < MARGIN + 60) break; // don't overflow page

    const { r, g, b } = hexToRgb(colors[i].value);
    colorPage.drawRectangle({
      x, y: sy - SWATCH_SIZE, width: SWATCH_SIZE, height: SWATCH_SIZE,
      color: rgb(r, g, b),
    });
    colorPage.drawText(colors[i].value.toUpperCase(), {
      x: x + SWATCH_SIZE + 10, y: sy - 15, size: 11, font: helveticaBold, color: rgb(0.1, 0.1, 0.1),
    });
    colorPage.drawText(`${colors[i].role} — ${colors[i].name}`, {
      x: x + SWATCH_SIZE + 10, y: sy - 30, size: 9, font: helvetica, color: rgb(0.4, 0.4, 0.4),
    });
    colorPage.drawText(`${colors[i].confidence} confidence`, {
      x: x + SWATCH_SIZE + 10, y: sy - 42, size: 8, font: helvetica, color: rgb(0.6, 0.6, 0.6),
    });
  }

  // --- Typography Page ---
  const typoPage = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  y = PAGE_HEIGHT - MARGIN;

  typoPage.drawText("Typography", {
    x: MARGIN, y: y - 20, size: 24, font: helveticaBold, color: rgb(0.1, 0.1, 0.1),
  });
  y -= 70;

  for (const font of data.identity.typography.slice(0, 8)) {
    typoPage.drawText(font.family, {
      x: MARGIN, y, size: 16, font: helveticaBold, color: rgb(0.1, 0.1, 0.1),
    });
    const details = [
      font.source ? `Source: ${font.source}` : null,
      font.confidence ? `Confidence: ${font.confidence}` : null,
    ].filter(Boolean).join("  •  ");
    typoPage.drawText(details, {
      x: MARGIN, y: y - 18, size: 9, font: helvetica, color: rgb(0.5, 0.5, 0.5),
    });
    y -= 45;
    if (y < MARGIN + 40) break;
  }

  // --- Visual Rules Page (if Session 2) ---
  if (data.visual) {
    const visualPage = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    y = PAGE_HEIGHT - MARGIN;

    visualPage.drawText("Visual Identity Rules", {
      x: MARGIN, y: y - 20, size: 24, font: helveticaBold, color: rgb(0.1, 0.1, 0.1),
    });
    y -= 60;

    if (data.visual.composition) {
      visualPage.drawText("Composition", {
        x: MARGIN, y, size: 14, font: helveticaBold, color: rgb(0.2, 0.2, 0.2),
      });
      y -= 20;
      const compText = typeof data.visual.composition === "string"
        ? data.visual.composition
        : JSON.stringify(data.visual.composition).slice(0, 200);
      visualPage.drawText(compText.slice(0, 80), {
        x: MARGIN, y, size: 10, font: helvetica, color: rgb(0.3, 0.3, 0.3),
      });
      y -= 30;
    }

    if (data.visual.anti_patterns?.length > 0) {
      visualPage.drawText(`Anti-Patterns (${data.visual.anti_patterns.length} rules)`, {
        x: MARGIN, y, size: 14, font: helveticaBold, color: rgb(0.2, 0.2, 0.2),
      });
      y -= 22;
      for (const ap of data.visual.anti_patterns.slice(0, 8)) {
        const severity = ap.severity === "hard" ? "✗" : "⚠";
        visualPage.drawText(`${severity}  ${ap.rule}`, {
          x: MARGIN + 10, y, size: 9, font: helvetica, color: rgb(0.3, 0.3, 0.3),
        });
        y -= 16;
        if (y < MARGIN + 40) break;
      }
    }
  }

  // --- Voice Page (if Session 3) ---
  if (data.messaging?.voice) {
    const voicePage = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    y = PAGE_HEIGHT - MARGIN;

    voicePage.drawText("Brand Voice", {
      x: MARGIN, y: y - 20, size: 24, font: helveticaBold, color: rgb(0.1, 0.1, 0.1),
    });
    y -= 60;

    const voice = data.messaging.voice;
    if (voice.tone?.descriptors?.length) {
      voicePage.drawText("Tone: " + voice.tone.descriptors.join(", "), {
        x: MARGIN, y, size: 11, font: helvetica, color: rgb(0.2, 0.2, 0.2),
      });
      y -= 25;
    }
    if (voice.vocabulary?.never_say?.length) {
      voicePage.drawText("Never Say:", {
        x: MARGIN, y, size: 12, font: helveticaBold, color: rgb(0.2, 0.2, 0.2),
      });
      y -= 18;
      for (const word of voice.vocabulary.never_say.slice(0, 10)) {
        voicePage.drawText(`•  ${word}`, {
          x: MARGIN + 10, y, size: 10, font: helvetica, color: rgb(0.4, 0.4, 0.4),
        });
        y -= 15;
      }
    }
  }

  // --- Footer on all pages ---
  const pages = pdf.getPages();
  for (let i = 0; i < pages.length; i++) {
    pages[i].drawText(`${data.config.client_name} Brand Guide  •  Page ${i + 1} of ${pages.length}  •  brandcode.studio`, {
      x: MARGIN, y: 25, size: 7, font: helvetica, color: rgb(0.7, 0.7, 0.7),
    });
  }

  return pdf.save();
}
